### ISSUE TITLE
error shiny.semantic theme/ui_icon

### ISSUE THREAD

**Issue by lunaseorim** [lunaseorim/datacampus#1]
Warning in check_semantic_theme(theme, full_url = FALSE) :
  Theme  United not recognized. Default used instead!
Error: 'uiicon' is not an exported object from 'namespace:shiny.semantic'

- [x] semantic error in shiny.app

**Comment by lunaseorim** [comment]
Resolved by re-installation
#package issue(dev version)

**Comment by shahreyar-abeer** [comment]
Hi there,

I'm getting the same error.
How did you solve it?
Was it resolved by reinstalling the dev version or the CRAN version?

Cheers,
Zauad
